image: python:3.6.5-slim

pages:
  script:
    - apt-get update
    - apt-get install -y make
    - pip install -r requirements.txt
    - pip install -e .
    - cd docs; make html
    - mv build/html ../public/
  artifacts:
    paths:
      - public
  only:
    - master
