image: python:alpine

pages:
  script:
    - pip install -r requirements.txt
    - apk --no-cache add make
    - cd docs; make html
    - mv build/html ../public/
  artifacts:
    paths:
      - public
  only:
    - master
