repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: requirements-txt-fixer
  # TODO: this throws import-error
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v1.9.1
  #   hooks:
  #     - id: pylint
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--quiet, --line-length=80, --safe, --py36]
