#!/usr/bin/env python

def flatten(tree):
	"""Finds all ``nodeIndex`` values belonging to a given merger tree
	
	Arguments:
		tree (list): merger tree generated by :func:`build`
	Returns:
		generator: to be fed as an argument to the ``list()`` function
	**References:**
		https://stackoverflow.com/a/2158532
	"""
	for node in tree:
		try:
			for subnode in flatten(node):
				yield subnode
		except:
			yield node

